### PR TITLE
Pull request to move BRCA Exchange literature search up to Max's pubMunch repo

### PR DESCRIPTION
**Pull request by rcurrie**
I've merged all the changes from maximilianh/pubMunch and run a preliminary crawl of a truth set we use from LOVD. 100% identical output from the current production version we're using. Most of these changes are in varFinder which likely isn't being used by other projects but a few read directly on the core. No immediate rush to accept but take a look and let's chat.

### CODE REVIEW

**Comment by rcurrie** [comment]
@diekhans Can't seem to add you as a reviewer but take a look and let's chat.

**Comment by diekhans** [comment]
I am traveling today  will give a look tomorrow 

-----Original Message-----

**Comment by maximilianh** [comment]
>Most of these changes are in varFinder which likely isn't being used by other projects but a 
>few read directly on the core
"core" can refer to RAM, for older people. What do you mean with "core"? Either way, don't worry about other projects, we're the only one using this source code.

This looks great, though I must admit I haven't looked at everything. There is one thing that I don't understand at all: "Warn instead of failing in varFinder when mapping coding and RNA". If you're doing just a logging.warn, how can we later figure out if there was a problem with mapping? If you remove this check, you're essentially removing all validation here. It certainly increases the sensitivity, but specificity should go down. You'll get a lot more false positives. If you remove the check, we should have some flag in the output. Also, I'm curious how much you gain in sensitivity if you remove this check. If the difference is only half a percent it may not be worth it. If the different is ~5% or so, it would be good why this is happening. Maybe there is some 1-off bug where we're getting the coding sequence? Or there is some common alternative way to specify the coordinates?

**Comment by diekhans** [comment]
I would agree that failure to map should be a category in the
output, not a warning.  This is probably less of a problem on
BRCA1/2, as they a fairly stable annotations.

**Comment by rcurrie** [comment]
Sorry for the slow response - on vacation in Portland. Good point @maximilianh, I'll take a bit closer look at the commit that warns in varFinder. Its a bit of a thicket given all the people that have worked on it for years and we're going from nothing to something. We also had clear feedback from the users, genomic councilors that false positives were fine given that their current alternative is google.

**Comment by maximilianh** [comment]
Yes, for BRCA genes this is all not a big deal. But it will be as soon as
you add more genes.

I'm not for removing these failed cases altogether.... but at least we
should have a flag "failedValidation" somewhere in the output.

**Comment by rcurrie** [comment]
@maximilianh Here's the local vars where the validation in dnaCodingPosition fails for a specific example:
```
ipdb> locals()
{'cdnaSeq': 'gacccccgagctgtgctgctcgcggccgccaccgccgggccccggccgtccctggctcccctcctgcctcgagaagggcagggcttctcagaggcttggcgggaaaaagaacggagggagggatcgcgctgagtataaaagccggttttcggggctttatctaactcgctgtagtaattccagcgagaggcagagggagcgagcgggcggccggctagggtggaagagccgggcgagcagagctgcgctgcgggcgtcctgggaagggagatccggagcgaatagggggcttcgcctctggcccagccctcccgctgatcccccagccagcggtccgcaacccttgccgcatccacgaaactttgcccatagcagcgggcgggcactttgcactggaacttacaacacccgagcaaggacgcgactctcccgacgcggggaggctattctgcccatttggggacacttccccgccgctgccaggacccgcttctctgaaaggctctccttgcagctgcttagacgctggatttttttcgggtagtggaaaaccagcagcctcccgcgacgatgcccctcaacgttagcttcaccaacaggaactatgacctcgactacgactcggtgcagccgtatttctactgcgacgaggaggagaacttctaccagcagcagcagcagagcgagctgcagcccccggcgcccagcgaggatatctggaagaaattcgagctgctgcccaccccgcccctgtcccctagccgccgctccgggctctgctcgccctcctacgttgcggtcacacccttctcccttcggggagacaacgacggcggtggcgggagcttctccacggccgaccagctggagatggtgaccgagctgctgggaggagacatggtgaaccagagtttcatctgcgacccggacgacgagaccttcatcaaaaacatcatcatccaggactgtatgtggagcggcttctcggccgccgccaagctcgtctcagagaagctggcctcctaccaggctgcgcgcaaagacagcggcagcccgaaccccgcccgcggccacagcgtctgctccacctccagcttgtacctgcaggatctgagcgccgccgcctcagagtgcatcgacccctcggtggtcttcccctaccctctcaacgacagcagctcgcccaagtcctgcgcctcgcaagactccagcgccttctctccgtcctcggattctctgctctcctcgacggagtcctccccgcagggcagccccgagcccctggtgctccatgaggagacaccgcccaccaccagcagcgactctgaggaggaacaagaagatgaggaagaaatcgatgttgtttctgtggaaaagaggcaggctcctggcaaaaggtcagagtctggatcaccttctgctggaggccacagcaaacctcctcacagcccactggtcctcaagaggtgccacgtctccacacatcagcacaactacgcagcgcctccctccactcggaaggactatcctgctgccaagagggtcaagttggacagtgtcagagtcctgagacagatcagcaacaaccgaaaatgcaccagccccaggtcctcggacaccgaggagaatgtcaagaggcgaacacacaacgtcttggagcgccagaggaggaacgagctaaaacggagcttttttgccctgcgtgaccagatcccggagttggaaaacaatgaaaaggcccccaaggtagttatccttaaaaaagccacagcatacatcctgtccgtccaagcagaggagcaaaagctcatttctgaagaggacttgttgcggaaacgacgagaacagttgaaacacaaacttgaacagctacggaactcttgtgcgtaaggaaaagtaaggaaaacgattccttctaacagaaatgtcctgagcaatcacctatgaacttgtttcaaatgcatgatcaaatgcaacctcacaaccttggctgagtcttgagactgaaagatttagccataatgtaaactgcctcaaattggactttgggcataaaagaacttttttatgcttaccatcttttttttttctttaacagatttgtatttaagaattgtttttaaaaaattttaagatttacacaatgtttctctgtaaatattgccattaaatgtaaataactttaataaaacgtttatagcagttacacagaatttcaatcctagtatatagtacctagtattataggtactataaaccctaattttttttatttaagtacattttgctttttaaagttgatttttttctattgtttttagaaaaaataaaataactggcaaatatatcattgagccaaatcttaaaaaaaaaaaaaaa', 
'expectAa': u'M', 'end': 1, 'start': 0, 'nuclEnd': 528, 'nuclSeq': 'ctg', 'nuclStart': 525, 'cdsStart': 525, 'foundAa': 'L', 'refseqId': u'NM_002467.4'}
```
No idea whether this is correct behavior or not. The asserting is only very occasionally thrown. I'll look into adding some sort of flag that indicates validation failed unless you think this points to some other underlying problem we should try and fix.

**Comment by diekhans** [comment]
I can't find a function dnaCodingPosition.  What is the variant
this is failing on?

NM_002467.4 is MYC, which has some interesting information about the CDS:

    There is evidence to show that alternative translation
    initiations from an upstream, in-frame non-AUG (CUG) and a
    downstream AUG start site result in the production of two isoforms
    with distinct N-termini. The synthesis of non-AUG initiated protein
    is suppressed in Burkitt's lymphomas, suggesting its importance in
    the normal function of this gene.

So I can see someone twisting their head to figure out how to encode
the alternate CDS.

Yet another case of our (as in all of bioinformatics) inability
to accurately represent genes.

**Comment by rcurrie** [comment]
Sorry, lib/varFinder.py => dnaAtCodingPos

So you think it may be trying to validate against the wrong isoform?

**Comment by maximilianh** [comment]
thanks Rob, this is exactly the type of sleuthing we would have to do to
find out why the validation fails. For examples like this, we'd need the
original text in the paper and its PMID and what variant finder mapped it
to to (you've provided this through the debugger, which is great, but I
think varfinder has a debug output that shows it) to say more.

The basic idea of varfinder (unlike NCBI's tmVar etc) is to check the
sequence to find the right gene. If you deactivate the sequence check, then
the number of wrong results that are output will go through the roof
(unless I've misunderstood something).

Sidenote: my goal for varfinder was to have much better debug information,
ideally the paper text would be shown and it would annotate the paper
("gene X is here and is probably linked to variant Y, because of
information Z"). People usually don't understand that the problem with text
mining is not so much the rules or the algorithm than the debugging. If the
debugging is bad, then you can spend hours trying to hunt down an obscure
case. If it's optimal (paper shown + annotations), then it takes a few
minutes.

**Comment by maximilianh** [comment]
Instead of hunting down examples though, you can do one simple
experiment here: take back this single change and see how much it
changes performance. With "performance" I mean its usual definition in
information retrieval, sensitivity/specificity (or the alternatives,
like precision/recall/accuracy, etc), not the histogram of variant
counts (even though that's interesting too, but for other questions).

**Comment by rcurrie** [comment]
@maximilianh Want to clarify what you mean by take back. As originally coded the assertion stopped the finder. My change added a logging message and then returned None,None,None which is what other control flows in that function do when they are unable to validate. Walking the stack back at this:

dnaAtCodingPos ->mapToCodingAndRna ->groundVariant->continue if None so it fails to ground the variant to a gene if I understand this correctly.

So I don't think we need a new flag but rather returning None,None,None has the desired behavior - just need a more detailed error message then "foundAa != expectAa" possibly.

Here's the console output running with debug on previous to the assertion being thrown:
```
INFO    -codVars: []                                                                                      [59/1974]INFO    -rnaVars: []
INFO    -beds: []
DEBUG   -Entrez gene 9020 = symbol MAP3K14
DEBUG   -Trying to ground VariantDescription(mutType=u'sub',seqType=u'prot',seqId=u'None',geneId=u'',start=u'1',end
=u'2',origSeq=u'M',mutSeq=u'H',origStr=u'[M1H',offset=u'0') to entrez gene 9020 / MAP3K14
DEBUG   -Entrez gene 9020 is mapped to proteins NP_003945.2
INFO    -vStart: 0
INFO    -vEnd: 1
INFO    -len(seq): 947
DEBUG   -Seq match: Found M at pos 0-1 in seq NP_003945.2
DEBUG   -Paranoia check: making sure that codons from 0-1 in NM_003954.4 correspond to M
DEBUG   -CDS start is 125, nucl pos is 125, codon is atg
DEBUG   -Looking for possible DNA change. Aa change M -> H, original dna ATG
DEBUG   -No possible DNA change found (max 1 bp change).
INFO    -protVars: [VariantDescription(mutType=u'sub',seqType=u'prot',seqId=u'NP_003945.2',geneId=u'',start=u'1',en
d=u'2',origSeq=u'M',mutSeq=u'H',origStr=u'[M1H',offset=u'0')]
INFO    -codVars: []
INFO    -rnaVars: []
INFO    -beds: []
DEBUG   -Entrez gene 4609 = symbol MYC
DEBUG   -Trying to ground VariantDescription(mutType=u'sub',seqType=u'prot',seqId=u'None',geneId=u'',start=u'1',end
=u'2',origSeq=u'M',mutSeq=u'H',origStr=u'[M1H',offset=u'0') to entrez gene 4609 / MYC
DEBUG   -Entrez gene 4609 is mapped to proteins NP_002458.2
INFO    -vStart: 0
INFO    -vEnd: 1
INFO    -len(seq): 454
DEBUG   -Seq match: Found M at pos 0-1 in seq NP_002458.2
DEBUG   -Paranoia check: making sure that codons from 0-1 in NM_002467.4 correspond to M
DEBUG   -CDS start is 525, nucl pos is 525, codon is ctg
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)

...

AssertionError:
> /pubMunch/lib/varFinder.py(999)dnaAtCodingPos()
    997     logger.debug("CDS start is %d, nucl pos is %d, codon is %s" % (cdsStart, nuclStart, nuclSeq))
    998     if not doShuffle:
--> 999         assert(foundAa == expectAa)
   1000     return nuclSeq, nuclStart, nuclEnd
   1001
```

**Comment by maximilianh** [comment]
Oh! Sorry. I misread the whole thing, I clearly should have looked into the
code first!

Yes, this is my paranoia check. I only put in asserts when something really
should not happen.

Let's look at this example:

It finds "M1H" in the text, which is obviously false positive nonsense and
tries to map it to https://www.ncbi.nlm.nih.gov/protein/NP_002458.2.
Unfortunately, NP_002458.2 happens to have a M as the first codon. But
according to varFinder the CDS start of
https://www.ncbi.nlm.nih.gov/nuccore/NM_002467.4  has the codon CTG, which
translates usually to L/Leu/Leucine in most cases, but the start position.
CTG is actually M at this position. So this is a bug. The assert was
correct in stopping.

So the fix for this would be to:
- make sure that when amino acid lookups are performed, it uses "M" when
the position is 0 and the codon is CTG.
- but really, how likely is it that we get variants at  position 1?  We
could check if we ever have any start codon mutation in Clinvar. If there
is none, we could simply say that anything with a start position==1 won't
be a valid variant... :-)

**Comment by diekhans** [comment]
I am not clear on how you are running this and what the output
file is.  However, I think it would be good to have the output
contain the misses due to not being able to map, as oppose to
just found/not found.

This is a common enough occurrence that it shouldn't be a
warning or error but part of the standard results.

**Comment by diekhans** [comment]
Another wonder of biology defeating our naive databases,
CTG is translate to M instead of L if it is the start codon.

**Comment by rcurrie** [comment]
Looks like this corner case (position 0) was the only cause of the assertion. I'm running through the full crawl (15k papers) to verify and if it completes propose that the assertion is only thrown if its not position 0 and it M and L.

**Comment by maximilianh** [comment]
Great!!

**Comment by rcurrie** [comment]
Good news - the case where the variant is at the start codon was the only one where the assertion was failing - at least for 15k papers with BRCA in the title or abstract. I've added a new [commit](https://github.com/maximilianh/pubMunch/pull/17/commits/cb70b0ff503c7bb663de27e1e071fd174df82db3) and just to be sure will re-run it through the 15k find step. Take a look and see if it correctly captures the case and if you are ok with the change.

**Comment by rcurrie** [comment]
Whoa - guess that is a yes! Will report back it if runs completely and if so close this all out. Good to be back with origin/master :-)

**Comment by maximilianh** [comment]
Looks great, I've accepted the pull request. Thanks Rob!

>

**Pull request merged**
